services:
  codefact-ft:
    image: node:20.16.0-alpine
    container_name: codefact-ft
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped