version: '3'   
services:      
  vite-app:   
    image: node:20.16.0-alpine  
    container_name: vite-app  
    working_dir: /app   
    volumes:
      - ./:/app   
      - /app/node_modules  
    ports:
      - "3000:3000"   
    command: sh -c "npm install && npm run dev"   
    environment:
      - CHOKIDAR_USEPOLLING=true  
    restart: unless-stopped  


   