export const APPOINTMENT_REQUEST = {
    APPROVE: "APPROVE",
    REJECT: "REJECT",
    CANCEL: "CANCEL",
};

export const APPOINMENT_STATUS = {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED",
    FINISHED: "FINISHED",
}

export const STATUS_LABELS: Record<string, string> = {
    [APPOINMENT_STATUS.PENDING]: "Pendiente",
    [APPOINMENT_STATUS.ACCEPTED]: "Aceptado",
    [APPOINMENT_STATUS.REJECTED]: "Rechazado",
    [APPOINMENT_STATUS.CANCELLED]: "Cancelado",
    [APPOINMENT_STATUS.COMPLETED]: "Completado",
    [APPOINMENT_STATUS.FINISHED]: "Finalizado",
  };
  