export const APPOINTMENT_REQUEST = {
    APPROVE: "APPROVE",
    REJECT: "REJECT",
    CANCEL: "CANCEL",
};

export const APPOINMENT_STATUS = {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
    CANCELED: "CANCELED",
    COMPLETED: "COMPLETED",
}